issuer: https://accounts.google.com
subject_pattern: '[0-9]+'
claim_pattern:
  email: '.*@jgardner-grype-chainguard-dev\.iam\.gserviceaccount\.com'
# grypedb-3z1y-dlv@vaikas-chainguard.iam.gserviceaccount.com
#subject: 110743266410577433854

permissions:
  contents: read
